'use client'

import { checkIsPublicRoute } from '@/functions/check-is-public-route'
import './globals.css'
import { Inter } from 'next/font/google'
import {usePathname} from 'next/navigation'
import { PrivateRoute } from '@/components/Private'
import { Toaster } from 'react-hot-toast'
import ProvidersWrapper from '@/components/SessionWrapper/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  const isPublicPage = checkIsPublicRoute(pathname!)

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersWrapper>
          <div>
            <Toaster/>
            {isPublicPage && children}

            {!isPublicPage && <PrivateRoute>{children}</PrivateRoute>}
          </div>
        </ProvidersWrapper>
      </body>
    </html>
  )
}
